title: TalknPaste Support
description: Voice to clipboard in one click - Support & Documentation
baseurl: "/talknpaste-support"
url: "https://jakobwong.github.io"

# Disable Jekyll themes - use custom layout
# theme: jekyll-theme-minimal

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge

# Author
author:
  name: TalknPaste Team
  email: support@talknpaste.app

# Social
github_username: jakobwong

# SEO
lang: en_US
google_analytics: # Add your GA tracking ID if needed

# Sass configuration
sass:
  style: compressed

# Exclude files
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - assets/css/style.scss