title: TalknPaste Support
description: Voice to clipboard in one click - Support & Documentation
baseurl: "/talknpaste-support"
url: "https://jakobwong.github.io"

# Completely disable Jekyll themes
theme: null
remote_theme: null

# GitHub Pages settings
plugins: []

# Markdown settings
markdown: kramdown
highlighter: rouge

# Force minimal processing
incremental: false
safe: true
strict_front_matter: true

# Author
author:
  name: TalknPaste Team
  email: support@talknpaste.app

# Social
github_username: jakobwong

# SEO
lang: en_US

# Exclude files
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock