title: TalknPaste Support
description: Voice to clipboard in one click - Support & Documentation
baseurl: "/talknpaste-support"
url: "https://jakobwong.github.io"

# GitHub Pages settings - no theme
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
highlighter: rouge

# Author
author:
  name: TalknPaste Team
  email: support@talknpaste.app

# Social
github_username: jakobwong

# SEO
lang: en_US

# Exclude files
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock